-- 현대지게차 경기북부판매 (김서정 과장, hj5321006@naver.com) 전용 신규 채널
-- 현대CM(hyundaicm_tasks) 기능을 동일하게 클론. 테이블/버킷/역할 완전 분리, 외부 파트너 없음(admin + 담당자 단일 티어).

-- ── 1) 역할 헬퍼 함수 ──────────────────────────────────────
create or replace function public.is_brother_staff()
returns boolean language sql stable as $$
  select public.is_admin_level() or coalesce((auth.jwt()->>'email'), '') = 'hj5321006@naver.com';
$$;

create or replace function public.is_brother_sales_rep()
returns boolean language sql stable as $$
  select coalesce((auth.jwt()->>'email'), '') = 'hj5321006@naver.com';
$$;

-- ── 2) 메인 테이블 ────────────────────────────────────────
create table if not exists public.brother_tasks (
  id                      bigint generated by default as identity primary key,
  customer_type           text not null default '개인',
  customer_name           text not null,
  customer_phone          text,
  company_name            text,
  ceo_name                text,
  equipment_ton           text,
  purchase_amount         bigint,
  vehicle_amount          bigint,
  attach_amount           bigint,
  installment_principal   bigint,
  grace_period            integer,
  installment_period      integer,
  finance_company         text,
  interest_rate           numeric,
  incentive               numeric,
  nice_score              integer,
  credit_rate             numeric,
  credit_incentive        numeric,
  biz_history             text,
  loan_limit              bigint,
  credit_note             text,
  has_tax_invoice         boolean,
  vat_deferred            boolean,
  vat_deferred_amount     bigint,
  loan_period             integer,
  sales_rep               text,
  sales_rep_phone         text,
  status                  text not null default '접수',
  special_note            text,
  doc_id_card             text,
  doc_employment          text,
  doc_income               text,
  doc_estimate            text,
  doc_excavator_license   text,
  doc_etc                 text,
  created_at              timestamptz not null default now(),
  closed_at               timestamptz,
  phone_scrubbed_at       timestamptz,
  case_no                 text,
  legacy_no               text,
  gcal_task_id            text,
  repayment_sent_at       timestamptz,
  repayment_sent_channel  text,
  repayment_sent_to       text,
  skip_sales_rep_alert    boolean not null default false
);

comment on column public.brother_tasks.skip_sales_rep_alert is
  '체크 시 이 딜의 카카오 알림톡/목록 조회에서 담당 영업사원(김서정)을 제외함. admin만 설정 가능(UI에서 admin에게만 노출).';

create table if not exists public.brother_etc_docs (
  id            bigint generated by default as identity primary key,
  task_id       bigint not null references public.brother_tasks(id) on delete cascade,
  storage_path  text not null,
  file_name     text not null,
  file_size     bigint,
  uploaded_at   timestamptz not null default now()
);

create table if not exists public.brother_holds (
  id            bigint generated by default as identity primary key,
  record_id     text not null,
  scheduled_at  timestamptz not null,
  note          text,
  recipients    text[] not null default '{}',
  is_sent       boolean not null default false,
  created_at    timestamptz not null default now(),
  unique (record_id)
);

create table if not exists public.brother_vehicle_reg_doc_uploads (
  id            uuid primary key default gen_random_uuid(),
  record_id     text not null,
  uploaded_by   uuid not null,
  storage_path  text not null,
  file_name     text not null,
  file_size     bigint,
  uploaded_at   timestamptz not null default now(),
  expires_at    timestamptz not null default now() + interval '72:00:00'
);

create table if not exists public.brother_tax_invoice_uploads (
  id            uuid primary key default gen_random_uuid(),
  record_id     text not null,
  uploaded_by   uuid not null,
  storage_path  text not null,
  file_name     text not null,
  file_size     bigint,
  invoice_type  text not null default 'vehicle',
  uploaded_at   timestamptz not null default now(),
  expires_at    timestamptz not null default now() + interval '72:00:00'
);

-- ── 3) RLS ────────────────────────────────────────────────
alter table public.brother_tasks enable row level security;
alter table public.brother_etc_docs enable row level security;
alter table public.brother_holds enable row level security;
alter table public.brother_vehicle_reg_doc_uploads enable row level security;
alter table public.brother_tax_invoice_uploads enable row level security;

revoke all on public.brother_tasks from anon;
revoke all on public.brother_etc_docs from anon;
revoke all on public.brother_holds from anon;
revoke all on public.brother_vehicle_reg_doc_uploads from anon;
revoke all on public.brother_tax_invoice_uploads from anon;

create policy brother_tasks_select on public.brother_tasks for select
  using (
    public.is_brother_staff()
    and not (coalesce(skip_sales_rep_alert, false) and public.is_brother_sales_rep())
  );
create policy brother_tasks_insert on public.brother_tasks for insert
  with check (public.is_brother_staff());
create policy brother_tasks_update on public.brother_tasks for update
  using (
    public.is_brother_staff()
    and not (coalesce(skip_sales_rep_alert, false) and public.is_brother_sales_rep())
  )
  with check (
    public.is_brother_staff()
    and not (coalesce(skip_sales_rep_alert, false) and public.is_brother_sales_rep())
  );
create policy brother_tasks_delete on public.brother_tasks for delete
  using (public.is_admin_level());

create policy brother_etc_docs_select on public.brother_etc_docs for select using (public.is_brother_staff());
create policy brother_etc_docs_insert on public.brother_etc_docs for insert with check (public.is_brother_staff());
create policy brother_etc_docs_update on public.brother_etc_docs for update using (public.is_brother_staff()) with check (public.is_brother_staff());
create policy brother_etc_docs_delete on public.brother_etc_docs for delete using (public.is_brother_staff());

create policy brother_holds_all on public.brother_holds for all
  using (public.is_brother_staff()) with check (public.is_brother_staff());

create policy brother_vehicle_reg_doc_uploads_select on public.brother_vehicle_reg_doc_uploads for select using (public.is_brother_staff());
create policy brother_vehicle_reg_doc_uploads_insert on public.brother_vehicle_reg_doc_uploads for insert with check (public.is_brother_staff());
create policy brother_vehicle_reg_doc_uploads_update on public.brother_vehicle_reg_doc_uploads for update using (public.is_brother_staff()) with check (public.is_brother_staff());
create policy brother_vehicle_reg_doc_uploads_delete on public.brother_vehicle_reg_doc_uploads for delete using (public.is_admin_level());

create policy brother_tax_invoice_uploads_all on public.brother_tax_invoice_uploads for all
  using (public.is_brother_staff()) with check (public.is_brother_staff());

-- ── 4) 스토리지 버킷 ──────────────────────────────────────
insert into storage.buckets (id, name, public)
values ('brother_docs', 'brother_docs', false)
on conflict (id) do nothing;
insert into storage.buckets (id, name, public)
values ('brother-vehicle-reg-docs', 'brother-vehicle-reg-docs', false)
on conflict (id) do nothing;
insert into storage.buckets (id, name, public)
values ('brother-tax-invoices', 'brother-tax-invoices', false)
on conflict (id) do nothing;

create policy brother_docs_select on storage.objects for select
  using (bucket_id = 'brother_docs' and public.is_brother_staff());
create policy brother_docs_insert on storage.objects for insert
  with check (bucket_id = 'brother_docs' and public.is_brother_staff());
create policy brother_docs_update on storage.objects for update
  using (bucket_id = 'brother_docs' and public.is_brother_staff())
  with check (bucket_id = 'brother_docs' and public.is_brother_staff());
create policy brother_docs_delete on storage.objects for delete
  using (bucket_id = 'brother_docs' and public.is_admin_level());

create policy brother_vehicle_reg_docs_select on storage.objects for select
  using (bucket_id = 'brother-vehicle-reg-docs' and public.is_brother_staff());
create policy brother_vehicle_reg_docs_insert on storage.objects for insert
  with check (bucket_id = 'brother-vehicle-reg-docs' and public.is_brother_staff());
create policy brother_vehicle_reg_docs_delete on storage.objects for delete
  using (bucket_id = 'brother-vehicle-reg-docs' and public.is_admin_level());

create policy brother_tax_invoices_select on storage.objects for select
  using (bucket_id = 'brother-tax-invoices' and public.is_brother_staff());
create policy brother_tax_invoices_insert on storage.objects for insert
  with check (bucket_id = 'brother-tax-invoices' and public.is_brother_staff());
create policy brother_tax_invoices_delete on storage.objects for delete
  using (bucket_id = 'brother-tax-invoices' and public.is_admin_level());
